spring:
  datasource:
    connectionProperties: useUnicode=true;characterEncoding=utf-8
    data-source-class-name: org.h2.Driver
    password: doma
    url: jdbc:h2:mem:domadb;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: doma
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:data/data.sql
